spring:
  datasource:
    url: jdbc:mysql://localhost:3306/conference?useSSL=false
    username: root
    password: rootuser
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate.ddl-auto: update

